# Generated by Django 5.0.6 on 2024-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_company_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
