# Generated by Django 5.1 on 2024-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_requirement_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.AddField(
            model_name='request',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
