# Generated by Django 5.1 on 2024-09-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
