# Generated by Django 5.1 on 2024-10-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='partner_name',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
