# Generated by Django 5.1 on 2024-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_remove_company_partner_name_delete_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
