# Generated by Django 5.1 on 2024-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_user_resetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='resetcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
