# Generated by Django 5.1 on 2024-12-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_alter_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='connection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
