# Generated by Django 5.1 on 2024-12-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_company_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
