# Generated by Django 5.1 on 2024-12-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0028_alter_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, choices=[('Nepal', 'Nepal'), ('India', 'India'), ('Singapore', 'Singapore')], max_length=100, null=True),
        ),
    ]
