# Generated by Django 5.1 on 2024-12-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_alter_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.CharField(blank=True, choices=[('Client', 'Client'), ('Partner', 'Partner'), ('Both', 'Both')], default='Client', max_length=100, null=True),
        ),
    ]
