# Generated by Django 5.1 on 2024-12-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0030_company_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='partner_company',
            field=models.ForeignKey(blank=True, help_text='Select the partner company', limit_choices_to={'role': 'Partner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='crm_app.company'),
        ),
    ]
