# Generated by Django 5.0.4 on 2024-04-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='via',
            old_name='via_name',
            new_name='via_Name',
        ),
    ]
