# Generated by Django 5.0.6 on 2024-07-08 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='currency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.status'),
        ),
    ]
