# Generated by Django 5.0.6 on 2024-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='via',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Via',
        ),
    ]
