# Generated by Django 5.0.6 on 2024-07-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0002_remove_transaction_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='resecurityapp.contact'),
        ),
    ]
