# Generated by Django 5.0.6 on 2024-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0002_alter_staff_role_alter_requirement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
