# Generated by Django 5.0.4 on 2024-04-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0002_rename_via_name_via_via_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='via',
            old_name='via_Name',
            new_name='Name',
        ),
    ]
