# Generated by Django 5.0.4 on 2024-04-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0003_rename_via_name_via_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='via',
            old_name='Name',
            new_name='Via_Name',
        ),
    ]
