# Generated by Django 5.0.6 on 2024-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0003_partner_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
