# Generated by Django 5.0.6 on 2024-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0004_partner_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='Phone_Number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
