# Generated by Django 5.0.4 on 2024-04-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0004_rename_name_via_via_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='contact_person',
            new_name='Contact_Person',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='phone_number',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='requirement_description',
            new_name='Requirement_Description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='value',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='contact_person',
            new_name='Contact_Person',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_name',
            new_name='Partner_Name',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='requirement_name',
            new_name='Requirement_Name',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='sector_name',
            new_name='Sector_Name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='Status_Name',
        ),
    ]
