# Generated by Django 5.0.6 on 2024-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0005_partner_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Requirement_Type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='service',
        ),
        migrations.AddField(
            model_name='transaction',
            name='requirement',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
