# Generated by Django 5.0.4 on 2024-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0005_rename_company_name_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
