# Generated by Django 5.0.6 on 2024-07-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='Product_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='resecurityapp.product'),
        ),
    ]
