# Generated by Django 5.0.4 on 2024-04-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0006_alter_company_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Company_Name', models.CharField(max_length=100)),
                ('action', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='partner',
        ),
    ]
