# Generated by Django 5.0.6 on 2024-07-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0006_remove_transaction_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
