# Generated by Django 5.0.6 on 2024-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0008_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
