# Generated by Django 5.0.4 on 2024-04-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0010_company_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
    ]
