# Generated by Django 5.0.4 on 2024-04-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0011_remove_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='NPR', max_length=100),
        ),
    ]
