# Generated by Django 5.0.6 on 2024-08-01 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0011_contact_dob_contact_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
