# Generated by Django 5.0.4 on 2024-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0012_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(max_length=100),
        ),
    ]
