# Generated by Django 5.0.6 on 2024-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0012_requirement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
