# Generated by Django 5.0.6 on 2024-08-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0013_alter_requirement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
