# Generated by Django 5.0.4 on 2024-04-26 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0013_alter_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Partner_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='Referral_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
