# Generated by Django 5.0.6 on 2024-08-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0015_alter_requirement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
