# Generated by Django 5.0.2 on 2024-04-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0015_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.brand'),
        ),
        migrations.AlterField(
            model_name='company',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.requirement'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='via',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.via'),
        ),
    ]
