# Generated by Django 5.0.4 on 2024-05-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0016_company_brand_alter_company_requirement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirement',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='requirement',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Requirement_Name',
            new_name='Service_Name',
        ),
    ]
