# Generated by Django 5.0.4 on 2024-05-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0017_rename_requirement_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='requirement',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
