# Generated by Django 5.0.4 on 2024-05-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0018_company_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='Sector_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
