# Generated by Django 5.0.4 on 2024-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0020_alter_company_partner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Product_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
