# Generated by Django 5.0.4 on 2024-05-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0022_alter_company_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Partner_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
