# Generated by Django 5.0.4 on 2024-05-24 09:26

import resecurityapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0028_role_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.CharField(default=resecurityapp.models.Staff, max_length=100),
        ),
    ]
