# Generated by Django 5.0.4 on 2024-05-24 09:28

import resecurityapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0029_company_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.AddField(
            model_name='company',
            name='Created_By',
            field=models.EmailField(default=resecurityapp.models.Staff, max_length=100),
        ),
    ]
