# Generated by Django 5.0.4 on 2024-05-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0030_remove_company_created_by_company_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Created_By',
            field=models.CharField(max_length=100),
        ),
    ]
