# Generated by Django 5.0.2 on 2024-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0031_alter_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Created_By',
            field=models.CharField(default='Staff', max_length=100),
        ),
    ]
