# Generated by Django 5.0.2 on 2024-05-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0032_transaction_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Contact_Person',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.CreateModel(
            name='Contact_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='resecurityapp.company')),
            ],
        ),
    ]
