# Generated by Django 5.0.2 on 2024-05-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0033_remove_company_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Person',
            new_name='ContactPerson',
        ),
    ]
