# Generated by Django 5.0.2 on 2024-05-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0034_rename_contact_person_contactperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='contact_name',
            new_name='Contact_Name',
        ),
        migrations.RenameField(
            model_name='contactperson',
            old_name='phone_number',
            new_name='Phone_Number',
        ),
    ]
