# Generated by Django 5.0.2 on 2024-05-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0035_rename_contact_name_contactperson_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPerson',
            new_name='Contact',
        ),
    ]
