# Generated by Django 5.0.2 on 2024-05-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0036_rename_contactperson_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactPerson',
        ),
    ]
