# Generated by Django 5.0.4 on 2024-05-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0037_rename_contact_contactperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPerson',
            new_name='Contact',
        ),
    ]
