# Generated by Django 5.0.4 on 2024-05-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0038_rename_contactperson_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Requirement_Description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='company',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='company',
            name='service',
        ),
    ]
