# Generated by Django 5.0.4 on 2024-05-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0039_remove_company_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requirement_Type', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100, null=True)),
                ('Requirement_Description', models.TextField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resecurityapp.company')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.service')),
            ],
        ),
    ]
