# Generated by Django 5.0.4 on 2024-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0041_alter_brand_brand_name_alter_service_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Product_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Requirement_Type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Company_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
