# Generated by Django 5.0.4 on 2024-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0042_transaction_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Company_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Requirement_Type',
            field=models.CharField(max_length=100),
        ),
    ]
