# Generated by Django 5.0.4 on 2024-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0044_alter_transaction_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
