# Generated by Django 5.0.4 on 2024-05-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0045_alter_transaction_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Company_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Requirement_Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
