# Generated by Django 5.0.2 on 2024-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0052_alter_transaction_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Company_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Product_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
