# Generated by Django 5.0.4 on 2024-06-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resecurityapp', '0054_alter_transaction_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.brand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resecurityapp.service'),
        ),
    ]
